---
# tasks file for roles/agent-install
- name: install repo for centos
  ansible.builtin.yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
  when: ansible_distribution == "CentOS"

- name: install repo for debian/ubuntu
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
- name: install zabbix agent
  package:
    name: zabbix-agent
    update_cache: yes
    state: latest

- name: confirm agent with start on reboot
  service:
    name: zabbix-agent
    enabled: yes
  notify:
  - restart zabbix agent

- name: copy config file
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - restart zabbix agent

- name: make a log folder
  file:
    path: /var/log/zabbix-agent/
    state: directory
    recurse: yes
    owner: zabbix
    group: zabbix
  notify:
    - restart zabbix agent